#!/bin/bash

#TEST 1
../src/cvgTools --command=toWig --input_type=c --input=input/countsFiles/count9 --out_path=output/cov2wig/

DIFF=$(diff output/cov2wig/out1.wig correct/cov2wig/out1_0.wig)

if [ "$DIFF" != "" ]
then
    printf "\nTEST 1 FAILED: \n"
    printf "$DIFF\n\n"
else
    printf "test 1 passed\n"
fi


#TEST 2
../src/cvgTools --command=toWig --input_type=b --input=input/bedFiles/gaps --out_path=output/cov2wig/

DIFF=$(diff output/cov2wig/out2.wig correct/cov2wig/out2_0.wig)

if [ "$DIFF" != "" ]
then
    printf "\nTEST 2 FAILED: \n"
    printf "$DIFF\n\n"
else
    printf "test 2 passed\n"
fi


#TEST 3
../src/cvgTools --command=toWig --input_type=b --input=input/bedFiles/gaps2 --out_path=output/cov2wig/

DIFF=$(diff output/cov2wig/out3.wig correct/cov2wig/out2_0.wig)

if [ "$DIFF" != "" ]
then
    printf "\nTEST 3 FAILED: \n"
    printf "$DIFF\n\n"
else
    printf "test 3 passed\n"
fi


#TEST 4
../src/cvgTools --command=GeneAvg --input_type=c --input=input/countsFiles/geneCount2 --output=output/geneAvg/ --transcripts=input/transcripts/small.bed 

DIFF=$(diff output/geneAvg/geneOut correct/geneAvg/geneOut_GA_0.txt)

if [ "$DIFF" != "" ]
then
    printf "\nTEST 4 FAILED: \n"
    printf "$DIFF\n\n"
else
    printf "test 4 passed\n"
fi


#TEST5
../src/cvgTools --command=GenicWindows --input_type=c --input=input/countsFiles/geneCount2 --output=output/geneWig/ --transcripts=input/transcripts/small.bed

DIFF=$(diff output/geneWig/genic2.wig correct/geneWig/genic2_GW_0.wig)

if [ "$DIFF" != "" ]
then 
    printf "\nTEST 5 FAILED: \n"
    printf "$DIFF\n\n"
else
    printf "test 5 passed\n"
fi


#TEST6
../src/cvgTools --command=GeneAvg --input_type=c --input=input/countsFiles/geneCount2 --output=output/geneAvg/ --transcripts=input/transcripts/overlap.bed

DIFF=$(diff output/geneAvg/overlap correct/geneAvg/overlap_GA_0.txt)

if [ "$DIFF" != "" ]
then 
    printf "\nTEST 6 FAILED: \n"
    printf "$DIFF\n\n"
else
    printf "test 6 passed\n"
fi


#TEST7
../src/cvgTools --command=GenicWindows --input_type=c --input=input/countsFiles/geneCount2 --output=output/geneWig/ --transcripts=input/transcripts/overlap.bed

DIFF=$(diff output/geneWig/overlap.wig correct/geneWig/overlap_GW_0.wig)

if [ "$DIFF" != "" ]
then 
    printf "\nTEST 7 FAILED: \n"
    printf "$DIFF\n\n"
else
    printf "test 7 passed\n"
fi

printf "TESTS END\n"
