#!/bin/bash

#TEST 1
../src/cvgTools toWig -c input/countsFiles/count9 output/cov2wig/out1.wig

DIFF=$(diff output/cov2wig/out1.wig correct/cov2wig/out1.wig)

if [ "$DIFF" != "" ]
then
    printf "\nTEST 1 FAILED: \n"
    printf "$DIFF\n\n"
else
    printf "test 1 passed\n"
fi


#TEST 2
../src/cvgTools toWig -b input/bedFiles/gaps output/cov2wig/out2.wig

DIFF=$(diff output/cov2wig/out2.wig correct/cov2wig/out2.wig)

if [ "$DIFF" != "" ]
then
    printf "\nTEST 2 FAILED: \n"
    printf "$DIFF\n\n"
else
    printf "test 2 passed\n"
fi


#TEST 3
../src/cvgTools toWig -b input/bedFiles/gaps2 output/cov2wig/out3.wig

DIFF=$(diff output/cov2wig/out3.wig correct/cov2wig/out2.wig)

if [ "$DIFF" != "" ]
then
    printf "\nTEST 3 FAILED: \n"
    printf "$DIFF\n\n"
else
    printf "test 3 passed\n"
fi


#TEST 4
../src/cvgTools GeneAvg -c input/countsFiles/geneCount2 output/geneAvg/geneOut -t input/transcripts/small.bed 

DIFF=$(diff output/geneAvg/geneOut correct/geneAvg/geneOut)

if [ "$DIFF" != "" ]
then
    printf "\nTEST 4 FAILED: \n"
    printf "$DIFF\n\n"
else
    printf "test 4 passed\n"
fi


#TEST5
../src/cvgTools GenicWindows -c input/countsFiles/geneCount2 output/geneWig/genic2.wig -t input/transcripts/small.bed

DIFF=$(diff output/geneWig/genic2.wig correct/geneWig/genic2.wig)

if [ "$DIFF" != "" ]
then 
    printf "\nTEST 5 FAILED: \n"
    printf "$DIFF\n\n"
else
    printf "test 5 passed\n"
fi

printf "TESTS END\n"
printf "Checking for memory leaks...\n\n"

printf "\nTEST 1\n\n"
valgrind ../src/cvgTools toWig -c input/countsFiles/count9 output/cov2wig/out1.wig

printf "\nTEST 2\n\n"
valgrind ../src/cvgTools toWig -b input/bedFiles/gaps output/cov2wig/out2.wig

printf "\nTEST 3\n\n"
valgrind ../src/cvgTools toWig -b input/bedFiles/gaps2 output/cov2wig/out3.wig

printf "\nTEST 4\n\n"
valgrind ../src/cvgTools GeneAvg -c input/countsFiles/geneCount2 output/geneAvg/geneOut -t input/transcripts/small.bed 

printf "MEMORY CHECKING COMPLETE\n"
