#!/bin/bash

#TEST 1
../src/cvgTools --command=ToWig --input_type=c --input=input/countsFiles/count9 --out_path=output/cov2wig

DIFF=$(diff correct/cov2wig/out1.wig output/cov2wig/count9_0.wig)

if [ "$DIFF" != "" ]
then
    printf "\nTEST 1 FAILED: \n"
    #printf "$DIFF\n\n"
else
    printf "test 1 passed\n"
    rm output/cov2wig/count9_0.wig
fi


#TEST 2
../src/cvgTools --command=ToWig --input_type=b --input=input/bedFiles/gaps --out_path=output/cov2wig

DIFF=$(diff correct/cov2wig/out2.wig output/cov2wig/gaps_0.wig)

if [ "$DIFF" != "" ]
then
    printf "\nTEST 2 FAILED: \n"
    #printf "$DIFF\n\n"
else
    printf "test 2 passed\n"
    rm output/cov2wig/gaps_0.wig
fi


#TEST 3
../src/cvgTools --command=ToWig --input_type=b --input=input/bedFiles/gaps2 --out_path=output/cov2wig/

DIFF=$(diff correct/cov2wig/out2.wig output/cov2wig/gaps2_0.wig)

if [ "$DIFF" != "" ]
then
    printf "\nTEST 3 FAILED: \n"
    #printf "$DIFF\n\n"
else
    printf "test 3 passed\n"
    rm output/cov2wig/gaps2_0.wig 
fi


#TEST 4
../src/cvgTools --command=GeneAvg --input_type=c --input=input/countsFiles/geneCount2 --out_path=output/geneAvg/ --transcripts=input/transcripts/small.bed --options=exons --options=start_codons --options=stop_codons

DIFF=$(diff correct/geneAvg/geneOut output/geneAvg/geneCount2_GA_0.txt)
EXON_DIFF=$(diff correct/geneAvg/geneCount2_GA_EXONS_0.txt output/geneAvg/geneCount2_GA_EXONS_0.txt)
START_C_DIFF=$(diff correct/geneAvg/geneCount2_GA_START_CODONS_0.txt output/geneAvg/geneCount2_GA_START_CODONS_0.txt)
STOP_C_DIFF=$(diff correct/geneAvg/geneCount2_GA_STOP_CODONS_0.txt output/geneAvg/geneCount2_GA_STOP_CODONS_0.txt)

if [ "$DIFF" != "" ]
then
    printf "\nTEST 4 GENE AVG FAILED: \n"
    #printf "$DIFF\n\n"
elif [ "$EXON_DIFF" != "" ]
then
    printf "\nTEST 4 EXON AVG FAILED\n"
    #printf "$EXON_DIFF\n\n"
elif [ "$START_C_DIFF" != "" ]
then
    printf "\nTEST 4 START CODON AVG FAILED\n"
    #printf "$START_C_DIFF\n\n"
elif [ "$STOP_C_DIFF" != "" ]
then
    printf "\nTEST 4 STOP CODON AVG FAILED\n"
    #printf "$STOP_C_DIFF\n\n"
else
    printf "test 4 passed\n"
    rm output/geneAvg/geneCount2_GA_0.txt
    rm output/geneAvg/geneCount2_GA_EXONS_0.txt 
    rm output/geneAvg/geneCount2_GA_START_CODONS_0.txt
    rm output/geneAvg/geneCount2_GA_STOP_CODONS_0.txt
fi


#TEST5
../src/cvgTools --command=GenicWindows --input_type=c --input=input/countsFiles/geneCount2 --out_path=output/geneWig/ --transcripts=input/transcripts/small.bed

DIFF=$(diff correct/geneWig/genic2.wig output/geneWig/geneCount2_GW_0.wig)

if [ "$DIFF" != "" ]
then 
    printf "\nTEST 5 FAILED: \n"
    #printf "$DIFF\n\n"
else
    printf "test 5 passed\n"
    rm output/geneWig/geneCount2_GW_0.wig 
fi


#TEST6
../src/cvgTools --command=GeneAvg --input_type=c --input=input/countsFiles/geneCount2_O --out_path=output/geneAvg/ --transcripts=input/transcripts/overlap.bed --options=exons --options=start_codons --options=stop_codons --options=cds

DIFF=$(diff correct/geneAvg/overlap output/geneAvg/geneCount2_O_GA_0.txt)
EXON_DIFF=$(diff correct/geneAvg/geneCount2_O_GA_EXONS_0.txt output/geneAvg/geneCount2_O_GA_EXONS_0.txt)
START_C_DIFF=$(diff correct/geneAvg/geneCount2_O_GA_START_CODONS_0.txt output/geneAvg/geneCount2_O_GA_START_CODONS_0.txt)
STOP_C_DIFF=$(diff correct/geneAvg/geneCount2_O_GA_STOP_CODONS_0.txt output/geneAvg/geneCount2_O_GA_STOP_CODONS_0.txt)
CDS_DIFF=$(diff correct/geneAvg/geneCount2_O_GA_CDS_0.txt output/geneAvg/geneCount2_O_GA_CDS_0.txt)

if [ "$DIFF" != "" ]
then 
    printf "\nTEST 6 FAILED: \n"
    #printf "$DIFF\n\n"
elif [ "$EXON_DIFF" != "" ]
then
    printf "\nTEST 4 EXON AVG FAILED\n"
    #printf "$EXON_DIFF\n\n"
elif [ "$START_C_DIFF" != "" ]
then
    printf "\nTEST 4 START CODON AVG FAILED\n"
    #printf "$START_C_DIFF\n\n"
elif [ "$STOP_C_DIFF" != "" ]
then
    printf "\nTEST 4 STOP CODON AVG FAILED\n"
    #printf "$STOP_C_DIFF\n\n"
elif [ "$CDS_DIFF" != "" ]
then
    printf "\nTEST 4 CDS AVG FAILED\n"
    #printf "$CDS_DIFF\n\n"
else
    printf "test 6 passed\n"
    rm output/geneAvg/geneCount2_O_GA_0.txt 
    rm output/geneAvg/geneCount2_O_GA_EXONS_0.txt
    rm output/geneAvg/geneCount2_O_GA_START_CODONS_0.txt
    rm output/geneAvg/geneCount2_O_GA_STOP_CODONS_0.txt
    rm output/geneAvg/geneCount2_O_GA_CDS_0.txt
fi


#TEST7
../src/cvgTools --command=GenicWindows --input_type=c --input=input/countsFiles/geneCount2_O --out_path=output/geneWig/ --transcripts=input/transcripts/overlap.bed

DIFF=$(diff correct/geneWig/overlap.wig output/geneWig/geneCount2_O_GW_0.wig)

if [ "$DIFF" != "" ]
then 
    printf "\nTEST 7 FAILED: \n"
    #printf "$DIFF\n\n"
else
    printf "test 7 passed\n"
    rm output/geneWig/geneCount2_O_GW_0.wig
fi

#TEST8
../src/cvgTools --command=GenicWindows --input_type=c --input=input/countsFiles/geneCount2_O --out_path=output/geneWig/ --transcripts=input/transcripts/many_overlap.bed

DIFF=$(diff correct/geneWig/many_overlap.wig output/geneWig/geneCount2_O_GW_0.wig)

if [ "$DIFF" != "" ]
then 
    printf "\nTEST 8 FAILED: \n"
    #printf "$DIFF\n\n"
else
    printf "test 8 passed\n"
    rm output/geneWig/geneCount2_O_GW_0.wig
fi

#TEST9
../src/cvgTools  --command=PeakAvg --input_type=c --input=input/countsFiles/geneCount2 --transcripts=input/transcripts/small.bed --out_path=output/peakAvg/

DIFF=$(diff correct/peakAvg/geneCount2_PeakAvg_0.txt output/peakAvg/geneCount2_PeakAvg_0.txt)

if [ "$DIFF" != "" ]
then 
    printf "\nTEST 9 FAILED: \n"
    #printf "$DIFF\n\n"
else
    printf "test 9 passed\n"
    rm output/peakAvg/geneCount2_PeakAvg_0.txt
fi




#Test 10
../src/cvgTools --command=NaturalWinAvg --input_type=c --input=input/countsFiles/geneCount --out_path=output/natWindow/

DIFF=$(diff correct/natWindow/geneCount_NWA_0.txt output/natWindow/geneCount_NWA_0.txt)

if [ "$DIFF" != "" ]
then 
    printf "\nTEST 10 FAILED: \n"
    #printf "$DIFF\n\n"
else
    printf "test 10 passed\n"
    rm output/natWindow/geneCount_NWA_0.txt
fi



#Test 11
../src/cvgTools --command=NaturalWinAvg --input_type=c --input=input/countsFiles/geneCount2 --out_path=output/natWindow/

DIFF=$(diff correct/natWindow/geneCount2_NWA_0.txt output/natWindow/geneCount2_NWA_0.txt)

if [ "$DIFF" != "" ]
then 
    printf "\nTEST 11 FAILED: \n"
    #printf "$DIFF\n\n"
else
    printf "test 11 passed\n"
    rm output/natWindow/geneCount2_NWA_0.txt
fi



#Test 12
../src/cvgTools --command=NaturalWinAvg --input_type=c --input=input/countsFiles/geneCount2_O --out_path=output/natWindow/

DIFF=$(diff correct/natWindow/geneCount2_O_NWA_0.txt output/natWindow/geneCount2_O_NWA_0.txt)

if [ "$DIFF" != "" ]
then 
    printf "\nTEST 12 FAILED: \n"
    #printf "$DIFF\n\n"
else
    printf "test 12 passed\n"
    rm output/natWindow/geneCount2_O_NWA_0.txt
fi


printf "TESTS END\n"
